# Generated by Django 5.2.1 on 2025-05-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPolicy',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('coupon_policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=72)),
                ('discount_type', models.CharField(choices=[('FIXED_AMOUNT', 'FIXED_AMOUNT'), ('PERCENTAGE', 'PERCENT_AMOUNT')], max_length=24)),
                ('discount_value', models.PositiveIntegerField(choices=[('FIXED_AMOUNT', 'FIXED_AMOUNT'), ('PERCENTAGE', 'PERCENT_AMOUNT')])),
                ('minimum_order_amount', models.PositiveIntegerField()),
                ('maximum_order_amount', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'coupon_policy',
                'ordering': ['-coupon_policy_id'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('USED', 'USED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], max_length=10)),
                ('order_id', models.CharField(max_length=36)),
                ('used_at', models.DateTimeField()),
                ('coupon_policy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.couponpolicy')),
            ],
            options={
                'db_table': 'coupon',
                'ordering': ['-coupon_id'],
            },
        ),
    ]
