# Generated by Django 5.2.1 on 2025-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpolicy',
            name='description',
            field=models.CharField(max_length=72, null=True),
        ),
    ]
